name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '*/60 * * * *'

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.x'

      - name: Install pup
        run: go install github.com/ericchiang/pup@latest

      - name: Fetch and extract table data
        run: |
          TABLE_SELECTOR='markdown-accessibility-table table'
          TABLE_OUTPUT="leaderboard_data.csv"
          PUP_PATH="$HOME/go/bin/pup"

          if [ -f "$PUP_PATH" ]; then
            echo "Attempting to run pup to get title..."
            "$PUP_PATH" "title" "https://github.com/vectara/hallucination-leaderboard"
            echo "Attempting to run pup to get table..."
            PUP_OUTPUT=$("$PUP_PATH" "$TABLE_SELECTOR" "https://github.com/vectara/hallucination-leaderboard")
            echo "pup output: $PUP_OUTPUT"

            if [ -n "$PUP_OUTPUT" ]; then
              echo "pup ran and produced output. Proceeding with processing."
              echo "$PUP_OUTPUT" | \
              sed 's/<tr>/,/g;s/<[^>]*>//g;s/,/\n/g' | \
              awk 'NF > 0' > "$TABLE_OUTPUT"
            else
              echo "Error: pup did not produce any output for the table selector."
              exit 1
            fi
          else
            echo "Error: pup binary not found at $PUP_PATH"
            exit 1
          fi

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Commit and push if it changed
        run: |
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add leaderboard_data.csv
          timestamp=$(date -u)
          if ! git diff --staged --quiet; then
            git commit -m "Latest leaderboard data: ${timestamp}"
            git remote set-url origin git@github.com:${{ github.repository }}
            git pull --rebase origin ${{ github.ref_name }} || echo "No remote changes to pull"
            git push origin HEAD:${{ github.ref_name }}
          fi
